train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./visualize_data/images
      root_path_2: ./visualize_data/masks
      cache: none
      split_key: none
  wrapper:
    name: train
    args:
      inp_size: 1024
      augment: false
      interpolation_mode: "nearest"
      resampling_factor: 1
  batch_size: 4

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/img/eval
      root_path_2: ./load/masks/eval
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 1024
      interpolation_mode: "nearest"
      resampling_factor: 1
  batch_size: 1

test_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: ./load/img/test
      root_path_2: ./load/masks/test
      cache: none
      split_key: test
  wrapper:
    name: val
    args:
      inp_size: 1024
      interpolation_mode: "nearest"
      resampling_factor: 1
  batch_size: 1
